### ISSUE TITLE
Kafka::DeliveryFailed: Failed to send messages to topic/partition

### ISSUE THREAD

**Issue by bharthur** [karafka/waterdrop#28]
Keep getting this error. Not able to send messages to kafka cluster.

This is what I'm testing:
```
message = WaterDrop::Message.new('hits', {test: 76}.to_json)
message.send!
```

And this is what it results in:

```
Kafka::DeliveryFailed: Failed to send messages to hits/0
from /path/to/gem/ruby-kafka-0.3.15/lib/kafka/producer.rb:332:in `deliver_messages_with_retries'
```
WaterDrop.config

```
#<#<Class:0x007ffc8356a090>:0x007ffc835698e8
 @config={:connection_pool_timeout=>5, :send_messages=>true, :raise_on_failure=>true, :connection_pool_size=>25, :kafka=>#<Dry::Configurable::NestedConfig:0x007ffc850ca768 @klass=#<Class:0x007ffc850ca740>>}>
```
WaterDrop.config.kafka.hosts

```
["kafka://ubuntudock:9092", "kafka://ubuntudock:9093", "kafka://ubuntudock:9094"]
```

Result of operation.execute from /ruby-kafka-0.3.15/lib/kafka/producer.rb:`deliver_messages_with_retries'

```
Attempt 1
{#<Kafka::Broker:0x007ffe1e811a90 @connection=#<Kafka::Connection:0x007ffe1e811bf8 @client_id="ruby-kafka", @port=9093, @host="kafka2", @logger=#<Logger:0x007ffe1e858b20 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1e858af8 @datetime_format=nil>, @formatter=nil, @logdev=nil>, @instrumenter=#<Kafka::Instrumenter:0x007ffe1e858a80 @default_payload={:client_id=>"ruby-kafka"}, @backend=ActiveSupport::Notifications>, @connect_timeout=10, @socket_timeout=10, @ssl_context=nil>, @node_id=2, @logger=#<Logger:0x007ffe1e858b20 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1e858af8 @datetime_format=nil>, @formatter=nil, @logdev=nil>>=>#<Kafka::MessageBuffer:0x007ffe1e811860 @buffer={"hits"=>{0=>[#<Kafka::Protocol::Message:0x007ffe1e8125f8 @key=nil, @value="{\"test\":76}", @codec_id=0, @offset=-1, @create_time=2017-06-06 12:33:05 -0400, @bytesize=11>]}}, @size=1, @bytesize=11>}
Attempt 2
{#<Kafka::Broker:0x007ffe1e811a90 @connection=#<Kafka::Connection:0x007ffe1e811bf8 @client_id="ruby-kafka", @port=9093, @host="kafka2", @logger=#<Logger:0x007ffe1e858b20 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1e858af8 @datetime_format=nil>, @formatter=nil, @logdev=nil>, @instrumenter=#<Kafka::Instrumenter:0x007ffe1e858a80 @default_payload={:client_id=>"ruby-kafka"}, @backend=ActiveSupport::Notifications>, @connect_timeout=10, @socket_timeout=10, @ssl_context=nil>, @node_id=2, @logger=#<Logger:0x007ffe1e858b20 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1e858af8 @datetime_format=nil>, @formatter=nil, @logdev=nil>>=>#<Kafka::MessageBuffer:0x007ffe187eeb68 @buffer={"hits"=>{0=>[#<Kafka::Protocol::Message:0x007ffe1e8125f8 @key=nil, @value="{\"test\":76}", @codec_id=0, @offset=-1, @create_time=2017-06-06 12:33:05 -0400, @bytesize=11>]}}, @size=1, @bytesize=11>}
Attempt 3
{#<Kafka::Broker:0x007ffe1e811a90 @connection=#<Kafka::Connection:0x007ffe1e811bf8 @client_id="ruby-kafka", @port=9093, @host="kafka2", @logger=#<Logger:0x007ffe1e858b20 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1e858af8 @datetime_format=nil>, @formatter=nil, @logdev=nil>, @instrumenter=#<Kafka::Instrumenter:0x007ffe1e858a80 @default_payload={:client_id=>"ruby-kafka"}, @backend=ActiveSupport::Notifications>, @connect_timeout=10, @socket_timeout=10, @ssl_context=nil>, @node_id=2, @logger=#<Logger:0x007ffe1e858b20 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1e858af8 @datetime_format=nil>, @formatter=nil, @logdev=nil>>=>#<Kafka::MessageBuffer:0x007ffe1d880590 @buffer={"hits"=>{0=>[#<Kafka::Protocol::Message:0x007ffe1e8125f8 @key=nil, @value="{\"test\":76}", @codec_id=0, @offset=-1, @create_time=2017-06-06 12:33:05 -0400, @bytesize=11>]}}, @size=1, @bytesize=11>}
Attempt 1
{#<Kafka::Broker:0x007ffe187833b8 @connection=#<Kafka::Connection:0x007ffe187834a8 @client_id="ruby-kafka", @port=9093, @host="kafka2", @logger=#<Logger:0x007ffe1878dcc8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1878dc50 @datetime_format=nil>, @formatter=nil, @logdev=nil>, @instrumenter=#<Kafka::Instrumenter:0x007ffe1878db10 @default_payload={:client_id=>"ruby-kafka"}, @backend=ActiveSupport::Notifications>, @connect_timeout=10, @socket_timeout=10, @ssl_context=nil>, @node_id=2, @logger=#<Logger:0x007ffe1878dcc8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1878dc50 @datetime_format=nil>, @formatter=nil, @logdev=nil>>=>#<Kafka::MessageBuffer:0x007ffe18782ff8 @buffer={"hits"=>{0=>[#<Kafka::Protocol::Message:0x007ffe18783bd8 @key=nil, @value="{\"test\":76}", @codec_id=0, @offset=-1, @create_time=2017-06-06 12:33:08 -0400, @bytesize=11>]}}, @size=1, @bytesize=11>}
Attempt 2
{#<Kafka::Broker:0x007ffe187833b8 @connection=#<Kafka::Connection:0x007ffe187834a8 @client_id="ruby-kafka", @port=9093, @host="kafka2", @logger=#<Logger:0x007ffe1878dcc8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1878dc50 @datetime_format=nil>, @formatter=nil, @logdev=nil>, @instrumenter=#<Kafka::Instrumenter:0x007ffe1878db10 @default_payload={:client_id=>"ruby-kafka"}, @backend=ActiveSupport::Notifications>, @connect_timeout=10, @socket_timeout=10, @ssl_context=nil>, @node_id=2, @logger=#<Logger:0x007ffe1878dcc8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1878dc50 @datetime_format=nil>, @formatter=nil, @logdev=nil>>=>#<Kafka::MessageBuffer:0x007ffe17691f50 @buffer={"hits"=>{0=>[#<Kafka::Protocol::Message:0x007ffe18783bd8 @key=nil, @value="{\"test\":76}", @codec_id=0, @offset=-1, @create_time=2017-06-06 12:33:08 -0400, @bytesize=11>]}}, @size=1, @bytesize=11>}
Attempt 3
{#<Kafka::Broker:0x007ffe187833b8 @connection=#<Kafka::Connection:0x007ffe187834a8 @client_id="ruby-kafka", @port=9093, @host="kafka2", @logger=#<Logger:0x007ffe1878dcc8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1878dc50 @datetime_format=nil>, @formatter=nil, @logdev=nil>, @instrumenter=#<Kafka::Instrumenter:0x007ffe1878db10 @default_payload={:client_id=>"ruby-kafka"}, @backend=ActiveSupport::Notifications>, @connect_timeout=10, @socket_timeout=10, @ssl_context=nil>, @node_id=2, @logger=#<Logger:0x007ffe1878dcc8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffe1878dc50 @datetime_format=nil>, @formatter=nil, @logdev=nil>>=>#<Kafka::MessageBuffer:0x007ffe16d24698 @buffer={"hits"=>{0=>[#<Kafka::Protocol::Message:0x007ffe18783bd8 @key=nil, @value="{\"test\":76}", @codec_id=0, @offset=-1, @create_time=2017-06-06 12:33:08 -0400, @bytesize=11>]}}, @size=1, @bytesize=11>}
Kafka::DeliveryFailed: Failed to send messages to hits/0
from /path/to/gem/ruby-2.3.3@goliath/gems/ruby-kafka-0.3.15/lib/kafka/producer.rb:332:in `deliver_messages_with_retries'
```

**Comment by mensfeld** [comment]
Hello @bharthur. It seems like an internal ruby-kafka problem. Did you report it there?

**Comment by bharthur** [comment]
@mensfeld No, I thought I'll ask here first and see if I'm doing anything wrong. Please, can you take a look and let me know If I doing anything wrong here with WaterDrop? Any mistake in config?

**Comment by mach-kernel** [comment]
Are you running Kafka / Zookeeper in Docker by any chance? I have had a similar problem before. 

I have had this issue before when incorrectly setting the `advertised.host.name` config key (`KAFKA_ADVERTISED_HOST_NAME` on most Docker images). You _cannot_ use `localhost` for this and should the container's IP instead. Below is a `docker-compose` template that you can use with a container setup I know works: 

```yaml
version: '2'
services:
  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    restart: always
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: (docker container's IP address)
      KAFKA_ADVERTISED_PORT: (9092, but whatever you want if you NAT it)
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by bharthur** [comment]
@mach-kernel Yes, I'm using docker and this is what my docker-compose looks like:

```
version: '2'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zk-multiple-kafka-multiple/zoo1/data:/data
      - ./zk-multiple-kafka-multiple/zoo1/datalog:/datalog

  zoo2:
    image: zookeeper:3.4.9
    hostname: zoo2
    ports:
      - "2182:2182"
    environment:
        ZOO_MY_ID: 2
        ZOO_PORT: 2182
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zk-multiple-kafka-multiple/zoo2/data:/data
      - ./zk-multiple-kafka-multiple/zoo2/datalog:/datalog

  zoo3:
    image: zookeeper:3.4.9
    hostname: zoo3
    ports:
      - "2183:2183"
    environment:
        ZOO_MY_ID: 3
        ZOO_PORT: 2183
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zk-multiple-kafka-multiple/zoo3/data:/data
      - ./zk-multiple-kafka-multiple/zoo3/datalog:/datalog


  kafka1:
    image: confluentinc/cp-kafka:3.2.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      # add the entry "127.0.0.1    kafka1" to your /etc/hosts file
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-multiple-kafka-multiple/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka2:
    image: confluentinc/cp-kafka:3.2.1
    hostname: kafka2
    ports:
      - "9093:9093"
    environment:
      # add the entry "127.0.0.1    kafka1" to your /etc/hosts file
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9093"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-multiple-kafka-multiple/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka3:
    image: confluentinc/cp-kafka:3.2.1
    hostname: kafka3
    ports:
      - "9094:9094"
    environment:
      # add the entry "127.0.0.1    kafka1" to your /etc/hosts file
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9094"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-multiple-kafka-multiple/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3
```
